FROM omi-web-preproduction:0.1.0

USER root
WORKDIR /app

RUN find /app -mindepth 1 -maxdepth 1 -exec rm -rf {} +

COPY --chown=nextjs:nodejs standalone/web/app ./
COPY --chown=nextjs:nodejs static ./.next/static
COPY --chown=nextjs:nodejs public ./public

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
